set(BUILD_SHARED_LIBS ON CACHE BOOL "" FORCE)
# build only the release config
set(BUILD_CONFIGURATION_TYPES "Release" CACHE BOOL "" FORCE)
# build only selected libraries for now
set(BUILD_ZLIB ON CACHE BOOL "" FORCE)
set(BUILD_HDF5 ON CACHE BOOL "" FORCE)

set(BUILD_BOOST OFF CACHE BOOL "" FORCE)
set(BUILD_GFLAGS OFF CACHE BOOL "" FORCE)
set(BUILD_GLOG OFF CACHE BOOL "" FORCE)
set(BUILD_LEVELDB OFF CACHE BOOL "" FORCE)
set(BUILD_LMDB OFF CACHE BOOL "" FORCE)
set(BUILD_OPENBLAS OFF CACHE BOOL "" FORCE)
set(BUILD_OPENCV OFF CACHE BOOL "" FORCE)
set(BUILD_PROTOBUF OFF CACHE BOOL "" FORCE)
set(BUILD_SNAPPY OFF CACHE BOOL "" FORCE)


