

message(STATUS "Using custom FindMatio module")
set(${CMAKE_FIND_PACKAGE_NAME}_ROOT "${CMAKE_INSTALL_PREFIX}")
set(${CMAKE_FIND_PACKAGE_NAME}_FOUND TRUE)
set(${CMAKE_FIND_PACKAGE_NAME}_INCLUDE_DIR "${${CMAKE_FIND_PACKAGE_NAME}_ROOT}/include")
set(${CMAKE_FIND_PACKAGE_NAME}_LIBRARY_DEBUG "${${CMAKE_FIND_PACKAGE_NAME}_ROOT}/lib/matiod.lib")
set(${CMAKE_FIND_PACKAGE_NAME}_LIBRARY_RELEASE "${${CMAKE_FIND_PACKAGE_NAME}_ROOT}/lib/matio.lib")

set(${CMAKE_FIND_PACKAGE_NAME}_INCLUDE_DIRS ${${CMAKE_FIND_PACKAGE_NAME}_INCLUDE_DIR})

find_package(ZLIB REQUIRED)
find_package(HDF5 REQUIRED)

if(NOT TARGET ${CMAKE_FIND_PACKAGE_NAME})
    foreach(_lib ${HDF5_LIBRARIES} ${ZLIB_LIBRARIES})
        list(APPEND _libs ${lib})
    endforeach()
    add_library(${CMAKE_FIND_PACKAGE_NAME} STATIC IMPORTED)
    set_target_properties(${CMAKE_FIND_PACKAGE_NAME} PROPERTIES
    IMPORTED_LOCATION_RELEASE "${${CMAKE_FIND_PACKAGE_NAME}_LIBRARY_RELEASE}"
	IMPORTED_LOCATION_DEBUG "${${CMAKE_FIND_PACKAGE_NAME}_LIBRARY_DEBUG}"
    INTERFACE_INCLUDE_DIRECTORIES "${${CMAKE_FIND_PACKAGE_NAME}_INCLUDE_DIRS}"
    )
endif()

set(${CMAKE_FIND_PACKAGE_NAME}_LIBRARY ${CMAKE_FIND_PACKAGE_NAME})
set(${CMAKE_FIND_PACKAGE_NAME}_LIBRARIES ${CMAKE_FIND_PACKAGE_NAME} ${ZLIB_LIBRARIES} ${HDF5_LIBRARIES})

