message(STATUS "Using custom Find${CMAKE_FIND_PACKAGE_NAME} module")
set(${CMAKE_FIND_PACKAGE_NAME}_DIR "${CMAKE_INSTALL_PREFIX}/share/Caffe" CACHE PATH "")
set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_MULTITHREAD ON)
set(Boost_USE_STATIC_RUNTIME OFF)
add_definitions(-DBOOST_ALL_NO_LIB)
find_package(Boost COMPONENTS system thread filesystem date_time python regex)
find_package(gflags REQUIRED)
find_package(glog REQUIRED)
set(PROTOBUF_SRC_ROOT_FOLDER ${CMAKE_INSTALL_PREFIX})
find_package(Protobuf REQUIRED)
find_package(HDF5 REQUIRED)
find_package(LMDB REQUIRED)
find_package(LevelDB REQUIRED)
find_package(Snappy REQUIRED)
find_package(OpenCV REQUIRED)
find_package(OpenBLAS REQUIRED)
find_package(${CMAKE_FIND_PACKAGE_NAME} CONFIG NO_CMAKE_PACKAGE_REGISTRY NO_CMAKE_SYSTEM_PACKAGE_REGISTRY)
set(CAFFE_FOUND ${${CMAKE_FIND_PACKAGE_NAME}_FOUND})	
