message(STATUS "Using custom Find${CMAKE_FIND_PACKAGE_NAME} module")
set(${CMAKE_FIND_PACKAGE_NAME}_DIR "${CMAKE_INSTALL_PREFIX}/CMake" CACHE PATH "")
find_package(${CMAKE_FIND_PACKAGE_NAME} CONFIG NO_CMAKE_PACKAGE_REGISTRY NO_CMAKE_SYSTEM_PACKAGE_REGISTRY)
set(LMDB_FOUND ${${CMAKE_FIND_PACKAGE_NAME}_FOUND})	