function(buildem_debug_status)
	if(BUILDEM_STATUS_DEBUG)
		message(STATUS ${ARGN})
	endif()
endfunction()

macro(buildem_debug_arguments name prefix )
	if(BUILDEM_STATUS_DEBUG)
		set(_status "${name}() called with arguments:\n")
		foreach(_arg ${ARGN})
			set(_status "${_status}${_arg} = ${${prefix}_${_arg}}\n")
		endforeach()
		message(STATUS "${_status}")
	endif()
endmacro()